### ISSUE TITLE
Error with settings file in Windows

### ISSUE THREAD

**Issue by KollinsPlays** [entuland/tpad#2]
I get these 2 error lines with this mod each time I load the world:
2022-06-17 11:37:55: ERROR[Main]: Error writing configuration file: "C:\Minetest\bin\..\worlds\World1/mod_storage/tpad.custom.conf"
2022-06-17 11:37:55: ERROR[Main]: Error writing configuration file: "C:\Minetest\bin\..\worlds\World1/mod_storage/tpad.custom.conf"

I see this line of code in init.lua line 8:
tpad.settings_file = minetest.get_worldpath() .. "/mod_storage/" .. tpad.mod_name .. ".custom.conf"

This is on a Windows system using Minetest 5.5.1 x64 portable and it appears to be something with the code expecting to be on a Linux type system where paths use /, but it's being run on a Windows system where paths use \.

**Comment by entuland** [comment]
Not sure, I've developed these mods on Windows 10 myself and as far as I can tell those directory separators shouldn't make any difference - meaning that Lua should take care of handling them correctly no matter which one you use.

I'll try and test it with that version as soon as I can to see if I can find out what's going wrong.

**Comment by KollinsPlays** [comment]
I had a copy of 5.5.0 and tried with that version with the same error so I don't think it's a MT version thing. I manually created the mod_storage folder in my world's directory and loaded the world and the error is gone and the new folder has tpad.custom.conf in it. If I recall right, there was something in Linux that auto creates the directory structure if you do something like touch /usr/local/foo/bar/file.txt it will create any directories that don't exist, but Windows won't, so to put a file in a directory that doesn't exist, you must first create the directory.

**Comment by entuland** [comment]
Glad to know it's something "simpler" than the tricky directory separator thing, which seems (luckily) handled transparently.

To be honest, I always assumed that directory to be there (and also assumed a mod was not only not expected to check for the existence of such a folder, but that also a mod was not allowed writing anywhere else other than that specific mod_storage folder - i.e. I assumed a mod would not be able to create such a folder in first place, being one level higher than its permitted root, so to speak).

It's been years now that I haven't done any minetest modding so my memory and my understanding could be totally flawed about that.

Whenever I get time I'll investigate this further and see if I can throw at least a directory existence check (and a directory creation command if necessary _and_ allowed)

**Comment by entuland** [comment]
Latest commits on master branch should take care of the errors - not relying on a physical file anymore to store the max global / max total pads admin settings, they get stored in whatever get_mod_storage() relies on (could be the SQLite database or a file, but that's transparent to my code now)

If a custom config file happens to be there for those two admin params, the params will get copied over to the new storage system and the corresponding file will get deleted.
